name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate contribution graph
        uses: Platane/snk@v2
        with:
          github_user_name: vborgex
          outputs: |
            ./pacman-contribution-graph.svg
            ./pacman-contribution-graph-dark.svg

      - name: Push contribution graph
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pacman-contribution-graph*.svg
          git commit -m "update contribution graph" || echo "no changes"
          git push
